#= require modernizr-custom.min
#= require jquery
#= require jquery_ujs
#= require handlebars
#= require ember
#= require ember-data
#= require_self
#= require embardy
window.Embardy = Ember.Application.create()
#= require_tree .
